// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnpyQtzlGyVUYM3emzX36c5thLPILkAj0',
    appId: '1:417563716591:web:96d044ec8016909116641a',
    messagingSenderId: '417563716591',
    projectId: 'ndattempt-af437',
    authDomain: 'ndattempt-af437.firebaseapp.com',
    databaseURL: 'https://ndattempt-af437-default-rtdb.firebaseio.com',
    storageBucket: 'ndattempt-af437.appspot.com',
    measurementId: 'G-ELZEHH8S0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoYlgBn73CqyTKggh98mX-HobjF2J77Eg',
    appId: '1:417563716591:android:97f9b430a7d8a88216641a',
    messagingSenderId: '417563716591',
    projectId: 'ndattempt-af437',
    databaseURL: 'https://ndattempt-af437-default-rtdb.firebaseio.com',
    storageBucket: 'ndattempt-af437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATcBWVnS9CT7zjH-xL5EAzeptur3KwrxY',
    appId: '1:417563716591:ios:650da9ed3228a0d816641a',
    messagingSenderId: '417563716591',
    projectId: 'ndattempt-af437',
    databaseURL: 'https://ndattempt-af437-default-rtdb.firebaseio.com',
    storageBucket: 'ndattempt-af437.appspot.com',
    iosClientId: '417563716591-dlmug07tm5nlea4q4g8ibbir3nkf0cnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyfreedom',
  );
}
