// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF8KMn5-wrlp1AOsJ7u64uMLrDbyeaDdQ',
    appId: '1:466521881954:web:cbea8fc9a7b37a7e2b003b',
    messagingSenderId: '466521881954',
    projectId: 'proyek4-8d032',
    authDomain: 'proyek4-8d032.firebaseapp.com',
    storageBucket: 'proyek4-8d032.appspot.com',
    measurementId: 'G-FVDTCGS4KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW6UnBMBsn2BGQ9zw-i5ESHHkji_zCJHs',
    appId: '1:466521881954:android:b7dbd6057f425c562b003b',
    messagingSenderId: '466521881954',
    projectId: 'proyek4-8d032',
    storageBucket: 'proyek4-8d032.appspot.com',
  );
}
